name: jubilacion_inteligente
description: "Planificador de jubilación para Bolivia."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  fl_chart: ^0.66.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/img/jubilacion.png
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/icono_app.png"